### PR TITLE
Add missing dependency. This will fix #113

### LINKED ISSUE #113: eyaml: add puppetlabs/puppetserver_gem as an explicit dependency for PE 2015.3
FYI,

Was able to get eyaml configuration to work with the correct directories after adding "puppetlabs/puppetserver_gem" to my control repo.  

Might be worth calling that out as an explicit dependency for hiera EYAML configuration.

### PR DESCRIPTION
**Pull request by dhoppe**

### CODE REVIEW

**Comment by alexjfisher** [comment]
This isn't a hard dependency and also depends on the version of puppet? It's documented in the README.

**Comment by dhoppe** [comment]
As far as I know, we are going to drop the support for Puppet 3 and this is required by Puppet 4 FOSS and PE.

**Comment by juniorsysadmin** [comment]
If this is a Puppet4-only change, make sure the puppet3 branch is created etc

**Comment by dhoppe** [comment]
@juniorsysadmin I do not know which FOSS version is affected, but according to #113 it is Puppet Enterprise 2015.3.

**Comment by LMacchi** [comment]
This is still an issue in 2016.5, class cannot be applied without puppetserver_gem.

**Comment by pillarsdotnet** [comment]
@dhoppe -- Why is this closed?

**Comment by alexjfisher** [comment]
At the time, the dependency was a soft dependency.  Depending on which version of puppet you were managing, you'd have to have the correct gem module installed.  This was documented in the [README](https://github.com/voxpupuli/puppet-hiera/tree/beeab993225fa816b9bf4483259549de30417ebc#setup-requirements).

But... since we no longer support "Puppet Enterprise 3.3 or earlier", or "Puppet Enterprise 3.7 or 3.8", this change is now correct.

I can't reopen this PR as the original fork/branch has been deleted.  If anyone wants to open a new PR adding `puppetserver_gem` to the metadata.json and updating the README, I can't see why anyone would have any objections this time round.

**Pull request closed without merging**
